[package]
name = "rbgb"
version = "0.1.0"
edition = "2024"

[dependencies]
debug_print = "1.0.0"
lazy_static = "1.5.0"
ntest = "0.9.3"
sdl2 = {version = "0.37.0", features = ["bundled"] }
time = "0.3.41"
